version: '3'

services:


  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: kursUser
      POSTGRES_PASSWORD: kursPswd
      POSTGRES_DB: TEST
      PG_DATA: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/db/:/var/lib/postgresql/data/
    networks:
      - task_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: jon@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./.docker/pgadmin:/var/lib/pgadmin
    ports:
      - "8001:80"
    networks:
      - task_network

  backend:
    container_name: backend
    depends_on:
      - db
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    networks:
      - task_network

networks:
  task_network:
    name: task_network